/**
 * Mock данные для микрофронтендов
 * Данные из shared пакета
 */

export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Смартфон iPhone 14 Pro',
    description: 'Флагманский смартфон от Apple с Dynamic Island, процессором A16 Bionic и тройной камерой 48MP',
    price: 89990,
    oldPrice: 99990,
    discount: 10,
    images: ['https://via.placeholder.com/400x400/1a1a1a/ffffff?text=iPhone+14+Pro'],
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 342,
    inStock: true,
    stockQuantity: 15,
    brand: 'Apple',
    tags: ['смартфон', 'флагман', 'iOS'],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'Ноутбук MacBook Pro 14"',
    description: 'Профессиональный ноутбук с чипом M3 Pro, 18GB RAM, 512GB SSD',
    price: 189990,
    images: ['https://via.placeholder.com/400x400/2a2a2a/ffffff?text=MacBook+Pro'],
    category: 'electronics',
    rating: 4.9,
    reviewsCount: 156,
    inStock: true,
    stockQuantity: 8,
    brand: 'Apple',
    tags: ['ноутбук', 'профессиональный', 'M3'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '3',
    name: 'Беспроводные наушники AirPods Pro 2',
    description: 'Наушники с активным шумоподавлением, адаптивным аудио и персонализированным пространственным звуком',
    price: 21990,
    oldPrice: 24990,
    discount: 12,
    images: ['https://via.placeholder.com/400x400/ffffff/1a1a1a?text=AirPods+Pro'],
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 523,
    inStock: true,
    stockQuantity: 45,
    brand: 'Apple',
    tags: ['наушники', 'беспроводные', 'ANC'],
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '4',
    name: 'Толстовка Nike Sportswear',
    description: 'Удобная толстовка из хлопка с капюшоном и карманом-кенгуру',
    price: 4990,
    images: ['https://via.placeholder.com/400x400/000000/ffffff?text=Nike+Hoodie'],
    category: 'clothing',
    rating: 4.5,
    reviewsCount: 89,
    inStock: true,
    stockQuantity: 120,
    brand: 'Nike',
    tags: ['одежда', 'спорт', 'толстовка'],
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '5',
    name: 'Книга "Чистый код"',
    description: 'Роберт Мартин. Создание, анализ и рефакторинг кода',
    price: 1290,
    images: ['https://via.placeholder.com/400x400/4a90e2/ffffff?text=Clean+Code'],
    category: 'books',
    rating: 4.9,
    reviewsCount: 756,
    inStock: true,
    stockQuantity: 35,
    brand: 'Питер',
    tags: ['книга', 'программирование', 'разработка'],
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '6',
    name: 'Умная колонка Яндекс Станция',
    description: 'Умная колонка с Алисой, управление умным домом, качественный звук',
    price: 8990,
    oldPrice: 11990,
    discount: 25,
    images: ['https://via.placeholder.com/400x400/ff0000/ffffff?text=Yandex+Station'],
    category: 'electronics',
    rating: 4.6,
    reviewsCount: 234,
    inStock: true,
    stockQuantity: 28,
    brand: 'Яндекс',
    tags: ['умный дом', 'голосовой помощник', 'колонка'],
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-21'),
  },
  {
    id: '7',
    name: 'Кроссовки Adidas Ultraboost',
    description: 'Беговые кроссовки с амортизацией Boost и сетчатым верхом',
    price: 14990,
    images: ['https://via.placeholder.com/400x400/000000/ffffff?text=Ultraboost'],
    category: 'sports',
    rating: 4.8,
    reviewsCount: 167,
    inStock: true,
    stockQuantity: 52,
    brand: 'Adidas',
    tags: ['обувь', 'спорт', 'бег'],
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '8',
    name: 'Планшет iPad Air',
    description: 'Планшет с 10.9" дисплеем Liquid Retina, чипом M1 и поддержкой Apple Pencil',
    price: 64990,
    images: ['https://via.placeholder.com/400x400/e0e0e0/1a1a1a?text=iPad+Air'],
    category: 'electronics',
    rating: 4.7,
    reviewsCount: 289,
    inStock: true,
    stockQuantity: 19,
    brand: 'Apple',
    tags: ['планшет', 'iOS', 'творчество'],
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '9',
    name: 'Умные часы Apple Watch Series 9',
    description: 'Смарт-часы с датчиком температуры, двойным касанием и ярким дисплеем',
    price: 39990,
    oldPrice: 44990,
    discount: 11,
    images: ['https://via.placeholder.com/400x400/1a1a1a/ffffff?text=Apple+Watch'],
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 412,
    inStock: true,
    stockQuantity: 33,
    brand: 'Apple',
    tags: ['часы', 'фитнес', 'здоровье'],
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '10',
    name: 'Рюкзак для ноутбука Bobby',
    description: 'Антивор рюкзак с USB-портом для зарядки, водонепроницаемый',
    price: 3490,
    images: ['https://via.placeholder.com/400x400/4a4a4a/ffffff?text=Bobby+Backpack'],
    category: 'home',
    rating: 4.6,
    reviewsCount: 145,
    inStock: true,
    stockQuantity: 67,
    brand: 'XD Design',
    tags: ['рюкзак', 'для ноутбука', 'антивор'],
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '11',
    name: 'Игровая консоль PlayStation 5',
    description: 'Новейшая консоль от Sony с 4K графикой и молниеносной загрузкой',
    price: 49990,
    images: ['https://via.placeholder.com/400x400/0070cc/ffffff?text=PS5'],
    category: 'electronics',
    rating: 4.9,
    reviewsCount: 678,
    inStock: false,
    stockQuantity: 0,
    brand: 'Sony',
    tags: ['консоль', 'игры', 'PlayStation'],
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '12',
    name: 'Кофеварка DeLonghi',
    description: 'Автоматическая кофемашина с капучинатором и функцией самоочистки',
    price: 45990,
    oldPrice: 52990,
    discount: 13,
    images: ['https://via.placeholder.com/400x400/8b4513/ffffff?text=DeLonghi'],
    category: 'home',
    rating: 4.7,
    reviewsCount: 234,
    inStock: true,
    stockQuantity: 14,
    brand: 'DeLonghi',
    tags: ['кофеварка', 'кухня', 'автомат'],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
];

// Экспортируем данные по умолчанию
export default {
  MOCK_PRODUCTS,
};
